In [2]:
import pandas as pd
import numpy as np
import matplotlib as plt
import seaborn as sns

In [3]:
df=pd.read_csv('../data/hr.csv')

In [4]:
df

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,...,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,2,80,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,...,3,80,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,...,4,80,1,6,3,3,2,2,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1465,36,No,Travel_Frequently,884,Research & Development,23,2,Medical,1,2061,...,3,80,1,17,3,3,5,2,0,3
1466,39,No,Travel_Rarely,613,Research & Development,6,1,Medical,1,2062,...,1,80,1,9,5,3,7,7,1,7
1467,27,No,Travel_Rarely,155,Research & Development,4,3,Life Sciences,1,2064,...,2,80,1,6,0,3,6,2,0,3
1468,49,No,Travel_Frequently,1023,Sales,2,3,Medical,1,2065,...,4,80,0,17,3,2,9,6,0,8
1469,34,No,Travel_Rarely,628,Research & Development,8,3,Medical,1,2068,...,1,80,0,6,3,4,4,3,1,2

In [5]:
df.isnull().sum()

Age                         0
Attrition                   0
BusinessTravel              0
DailyRate                   0
Department                  0
DistanceFromHome            0
Education                   0
EducationField              0
EmployeeCount               0
EmployeeNumber              0
EnvironmentSatisfaction     0
Gender                      0
HourlyRate                  0
JobInvolvement              0
JobLevel                    0
JobRole                     0
JobSatisfaction             0
MaritalStatus               0
MonthlyIncome               0
MonthlyRate                 0
NumCompaniesWorked          0
Over18                      0
OverTime                    0
PercentSalaryHike           0
PerformanceRating           0
RelationshipSatisfaction    0
StandardHours               0
StockOptionLevel            0
TotalWorkingYears           0
TrainingTimesLastYear       0
WorkLifeBalance             0
YearsAtCompany              0
YearsInCurrentRole          0
YearsSinceLastPromotion     0
YearsWithCurrManager        0
dtype: int64

In [6]:
df.dtypes

Age                         int64
Attrition                     str
BusinessTravel                str
DailyRate                   int64
Department                    str
DistanceFromHome            int64
Education                   int64
EducationField                str
EmployeeCount               int64
EmployeeNumber              int64
EnvironmentSatisfaction     int64
Gender                        str
HourlyRate                  int64
JobInvolvement              int64
JobLevel                    int64
JobRole                       str
JobSatisfaction             int64
MaritalStatus                 str
MonthlyIncome               int64
MonthlyRate                 int64
NumCompaniesWorked          int64
Over18                        str
OverTime                      str
PercentSalaryHike           int64
PerformanceRating           int64
RelationshipSatisfaction    int64
StandardHours               int64
StockOptionLevel            int64
TotalWorkingYears           int64
TrainingTimesLastYear       int64
WorkLifeBalance             int64
YearsAtCompany              int64
YearsInCurrentRole          int64
YearsSinceLastPromotion     int64
YearsWithCurrManager        int64
dtype: object

In [7]:
df.duplicated().sum()

np.int64(0)

In [8]:
df.describe()

,Age,DailyRate,DistanceFromHome,Education,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
count,1470.000000,1470.000000,1470.000000,1470.000000,1470.0,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,...,1470.000000,1470.0,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000
mean,36.923810,802.485714,9.192517,2.912925,1.0,1024.865306,2.721769,65.891156,2.729932,2.063946,...,2.712245,80.0,0.793878,11.279592,2.799320,2.761224,7.008163,4.229252,2.187755,4.123129
std,9.135373,403.509100,8.106864,1.024165,0.0,602.024335,1.093082,20.329428,0.711561,1.106940,...,1.081209,0.0,0.852077,7.780782,1.289271,0.706476,6.126525,3.623137,3.222430,3.568136
min,18.000000,102.000000,1.000000,1.000000,1.0,1.000000,1.000000,30.000000,1.000000,1.000000,...,1.000000,80.0,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000
25%,30.000000,465.000000,2.000000,2.000000,1.0,491.250000,2.000000,48.000000,2.000000,1.000000,...,2.000000,80.0,0.000000,6.000000,2.000000,2.000000,3.000000,2.000000,0.000000,2.000000
50%,36.000000,802.000000,7.000000,3.000000,1.0,1020.500000,3.000000,66.000000,3.000000,2.000000,...,3.000000,80.0,1.000000,10.000000,3.000000,3.000000,5.000000,3.000000,1.000000,3.000000
75%,43.000000,1157.000000,14.000000,4.000000,1.0,1555.750000,4.000000,83.750000,3.000000,3.000000,...,4.000000,80.0,1.000000,15.000000,3.000000,3.000000,9.000000,7.000000,3.000000,7.000000
max,60.000000,1499.000000,29.000000,5.000000,1.0,2068.000000,4.000000,100.000000,4.000000,5.000000,...,4.000000,80.0,3.000000,40.000000,6.000000,4.000000,40.000000,18.000000,15.000000,17.000000

In [9]:
Q1=df['MonthlyIncome'].quantile(0.25)
Q3=df['MonthlyIncome'].quantile(0.75)

IQR=Q3-Q1

lower=Q1-1.5*IQR
upper=Q3+1.5*IQR

outliers=df[(df['MonthlyIncome']<lower) | (df['MonthlyIncome']>upper)]

outliers

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
25,53,No,Travel_Rarely,1282,Research & Development,5,3,Other,1,32,...,4,80,1,26,3,2,14,13,4,8
29,46,No,Travel_Rarely,705,Sales,2,4,Marketing,1,38,...,4,80,0,22,2,2,2,2,2,1
45,41,Yes,Travel_Rarely,1360,Research & Development,12,3,Technical Degree,1,58,...,4,80,0,23,0,3,22,15,15,8
62,50,No,Travel_Rarely,989,Research & Development,7,2,Medical,1,80,...,4,80,1,29,2,2,27,3,13,8
105,59,No,Non-Travel,1420,Human Resources,2,4,Human Resources,1,140,...,4,80,1,30,3,3,3,2,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1374,58,No,Travel_Rarely,605,Sales,21,3,Life Sciences,1,1938,...,3,80,1,29,2,2,1,0,0,0
1377,49,No,Travel_Frequently,1064,Research & Development,2,1,Life Sciences,1,1941,...,4,80,0,28,3,3,5,4,4,3
1401,55,No,Travel_Rarely,189,Human Resources,26,4,Human Resources,1,1973,...,1,80,1,35,0,3,10,9,1,4
1437,39,No,Non-Travel,105,Research & Development,9,3,Life Sciences,1,2022,...,3,80,0,21,3,2,6,0,1,3
1443,42,No,Travel_Rarely,300,Research & Development,2,3,Life Sciences,1,2031,...,1,80,0,24,2,2,22,6,4,14

In [10]:
df=df[(df['MonthlyIncome']>=lower) & (df['MonthlyIncome']<=upper)]

In [11]:
df.columns

Index(['Age', 'Attrition', 'BusinessTravel', 'DailyRate', 'Department',
       'DistanceFromHome', 'Education', 'EducationField', 'EmployeeCount',
       'EmployeeNumber', 'EnvironmentSatisfaction', 'Gender', 'HourlyRate',
       'JobInvolvement', 'JobLevel', 'JobRole', 'JobSatisfaction',
       'MaritalStatus', 'MonthlyIncome', 'MonthlyRate', 'NumCompaniesWorked',
       'Over18', 'OverTime', 'PercentSalaryHike', 'PerformanceRating',
       'RelationshipSatisfaction', 'StandardHours', 'StockOptionLevel',
       'TotalWorkingYears', 'TrainingTimesLastYear', 'WorkLifeBalance',
       'YearsAtCompany', 'YearsInCurrentRole', 'YearsSinceLastPromotion',
       'YearsWithCurrManager'],
      dtype='str')

In [12]:
df = df.rename(columns={
    'BusinessTravel': 'Travel',
    'Department': 'Dept',
    'DistanceFromHome': 'HomeDist',
    'EducationField': 'EduField',
    'EmployeeCount': 'EmpCount',
    'EmployeeNumber': 'EmpNo',
    'JobLevel': 'JobLvl',
    'JobRole': 'JobRole',
    'MaritalStatus': 'Marital',
    'MonthlyIncome': 'MonthlyInc',
    'MonthlyRate': 'MonthlyRate',
    'PercentSalaryHike': 'SalaryHike',
    'StandardHours': 'StdHours',
    'WorkLifeBalance': 'Work_Life_Bal',
})

In [13]:
df

,Age,Attrition,Travel,DailyRate,Dept,HomeDist,Education,EduField,EmpCount,EmpNo,...,RelationshipSatisfaction,StdHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,Work_Life_Bal,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,...,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,2,80,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,...,3,80,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,...,4,80,1,6,3,3,2,2,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1465,36,No,Travel_Frequently,884,Research & Development,23,2,Medical,1,2061,...,3,80,1,17,3,3,5,2,0,3
1466,39,No,Travel_Rarely,613,Research & Development,6,1,Medical,1,2062,...,1,80,1,9,5,3,7,7,1,7
1467,27,No,Travel_Rarely,155,Research & Development,4,3,Life Sciences,1,2064,...,2,80,1,6,0,3,6,2,0,3
1468,49,No,Travel_Frequently,1023,Sales,2,3,Medical,1,2065,...,4,80,0,17,3,2,9,6,0,8
1469,34,No,Travel_Rarely,628,Research & Development,8,3,Medical,1,2068,...,1,80,0,6,3,4,4,3,1,2

In [14]:
df.isna().sum()

Age                         0
Attrition                   0
Travel                      0
DailyRate                   0
Dept                        0
HomeDist                    0
Education                   0
EduField                    0
EmpCount                    0
EmpNo                       0
EnvironmentSatisfaction     0
Gender                      0
HourlyRate                  0
JobInvolvement              0
JobLvl                      0
JobRole                     0
JobSatisfaction             0
Marital                     0
MonthlyInc                  0
MonthlyRate                 0
NumCompaniesWorked          0
Over18                      0
OverTime                    0
SalaryHike                  0
PerformanceRating           0
RelationshipSatisfaction    0
StdHours                    0
StockOptionLevel            0
TotalWorkingYears           0
TrainingTimesLastYear       0
Work_Life_Bal               0
YearsAtCompany              0
YearsInCurrentRole          0
YearsSinceLastPromotion     0
YearsWithCurrManager        0
dtype: int64

In [15]:
df.head()

,Age,Attrition,Travel,DailyRate,Dept,HomeDist,Education,EduField,EmpCount,EmpNo,...,RelationshipSatisfaction,StdHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,Work_Life_Bal,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,...,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,2,80,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,...,3,80,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,...,4,80,1,6,3,3,2,2,2,2

In [16]:
df.tail()

,Age,Attrition,Travel,DailyRate,Dept,HomeDist,Education,EduField,EmpCount,EmpNo,...,RelationshipSatisfaction,StdHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,Work_Life_Bal,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
1465,36,No,Travel_Frequently,884,Research & Development,23,2,Medical,1,2061,...,3,80,1,17,3,3,5,2,0,3
1466,39,No,Travel_Rarely,613,Research & Development,6,1,Medical,1,2062,...,1,80,1,9,5,3,7,7,1,7
1467,27,No,Travel_Rarely,155,Research & Development,4,3,Life Sciences,1,2064,...,2,80,1,6,0,3,6,2,0,3
1468,49,No,Travel_Frequently,1023,Sales,2,3,Medical,1,2065,...,4,80,0,17,3,2,9,6,0,8
1469,34,No,Travel_Rarely,628,Research & Development,8,3,Medical,1,2068,...,1,80,0,6,3,4,4,3,1,2

In [17]:
df.sample(5)

,Age,Attrition,Travel,DailyRate,Dept,HomeDist,Education,EduField,EmpCount,EmpNo,...,RelationshipSatisfaction,StdHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,Work_Life_Bal,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
494,34,No,Travel_Rarely,204,Sales,14,3,Technical Degree,1,666,...,4,80,2,8,3,3,8,2,0,6
1150,35,No,Travel_Rarely,819,Research & Development,18,5,Life Sciences,1,1621,...,4,80,0,16,2,3,16,15,1,10
590,33,No,Travel_Rarely,213,Research & Development,7,3,Medical,1,817,...,4,80,0,14,3,4,13,9,3,7
702,30,No,Travel_Rarely,231,Sales,8,2,Other,1,982,...,1,80,1,10,2,4,8,4,7,7
1444,56,Yes,Travel_Rarely,310,Research & Development,7,2,Technical Degree,1,2032,...,4,80,1,14,4,1,10,9,9,8

In [18]:
df.shape

(1356, 35)

In [19]:
df.columns

Index(['Age', 'Attrition', 'Travel', 'DailyRate', 'Dept', 'HomeDist',
       'Education', 'EduField', 'EmpCount', 'EmpNo', 'EnvironmentSatisfaction',
       'Gender', 'HourlyRate', 'JobInvolvement', 'JobLvl', 'JobRole',
       'JobSatisfaction', 'Marital', 'MonthlyInc', 'MonthlyRate',
       'NumCompaniesWorked', 'Over18', 'OverTime', 'SalaryHike',
       'PerformanceRating', 'RelationshipSatisfaction', 'StdHours',
       'StockOptionLevel', 'TotalWorkingYears', 'TrainingTimesLastYear',
       'Work_Life_Bal', 'YearsAtCompany', 'YearsInCurrentRole',
       'YearsSinceLastPromotion', 'YearsWithCurrManager'],
      dtype='str')

In [20]:
df.info()
df.describe()

<class 'pandas.DataFrame'>
Index: 1356 entries, 0 to 1469
Data columns (total 35 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       1356 non-null   int64
 1   Attrition                 1356 non-null   str
 2   Travel                    1356 non-null   str
 3   DailyRate                 1356 non-null   int64
 4   Dept                      1356 non-null   str
 5   HomeDist                  1356 non-null   int64
 6   Education                 1356 non-null   int64
 7   EduField                  1356 non-null   str
 8   EmpCount                  1356 non-null   int64
 9   EmpNo                     1356 non-null   int64
 10  EnvironmentSatisfaction   1356 non-null   int64
 11  Gender                    1356 non-null   str
 12  HourlyRate                1356 non-null   int64
 13  JobInvolvement            1356 non-null   int64
 14  JobLvl                    1356 non-null   int64
 15  JobRole                   1356 non-null   str
 16  JobSatisfaction           1356 non-null   int64
 17  Marital                   1356 non-null   str
 18  MonthlyInc                1356 non-null   int64
 19  MonthlyRate               1356 non-null   int64
 20  NumCompaniesWorked        1356 non-null   int64
 21  Over18                    1356 non-null   str
 22  OverTime                  1356 non-null   str
 23  SalaryHike                1356 non-null   int64
 24  PerformanceRating         1356 non-null   int64
 25  RelationshipSatisfaction  1356 non-null   int64
 26  StdHours                  1356 non-null   int64
 27  StockOptionLevel          1356 non-null   int64
 28  TotalWorkingYears         1356 non-null   int64
 29  TrainingTimesLastYear     1356 non-null   int64
 30  Work_Life_Bal             1356 non-null   int64
 31  YearsAtCompany            1356 non-null   int64
 32  YearsInCurrentRole        1356 non-null   int64
 33  YearsSinceLastPromotion   1356 non-null   int64
 34  YearsWithCurrManager      1356 non-null   int64
dtypes: int64(26), str(9)
memory usage: 483.9 KB

,Age,DailyRate,HomeDist,Education,EmpCount,EmpNo,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLvl,...,RelationshipSatisfaction,StdHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,Work_Life_Bal,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
count,1356.000000,1356.000000,1356.000000,1356.000000,1356.0,1356.000000,1356.000000,1356.000000,1356.000000,1356.000000,...,1356.000000,1356.0,1356.000000,1356.000000,1356.000000,1356.000000,1356.000000,1356.000000,1356.000000,1356.000000
mean,36.038348,802.220501,9.351032,2.907817,1.0,1028.637906,2.715339,65.964602,2.729351,1.850295,...,2.702065,80.0,0.798673,10.036136,2.797935,2.757375,6.367994,4.019912,1.959440,3.929204
std,8.808835,403.498941,8.131071,1.026396,0.0,605.959746,1.090760,20.263728,0.715496,0.848097,...,1.081762,0.0,0.863374,6.583958,1.298490,0.710063,5.183808,3.416960,2.932798,3.427176
min,18.000000,102.000000,1.000000,1.000000,1.0,1.000000,1.000000,30.000000,1.000000,1.000000,...,1.000000,80.0,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000
25%,30.000000,465.750000,2.000000,2.000000,1.0,490.250000,2.000000,48.000000,2.000000,1.000000,...,2.000000,80.0,0.000000,6.000000,2.000000,2.000000,3.000000,2.000000,0.000000,2.000000
50%,35.000000,804.000000,7.000000,3.000000,1.0,1017.500000,3.000000,66.000000,3.000000,2.000000,...,3.000000,80.0,1.000000,9.000000,3.000000,3.000000,5.000000,3.000000,1.000000,3.000000
75%,41.000000,1157.000000,14.000000,4.000000,1.0,1568.250000,4.000000,83.250000,3.000000,2.000000,...,4.000000,80.0,1.000000,13.000000,3.000000,3.000000,9.000000,7.000000,2.000000,7.000000
max,60.000000,1499.000000,29.000000,5.000000,1.0,2068.000000,4.000000,100.000000,4.000000,4.000000,...,4.000000,80.0,3.000000,40.000000,6.000000,4.000000,40.000000,17.000000,15.000000,17.000000

In [21]:
df['JobLvl']

0       2
1       2
2       1
3       1
4       1
       ..
1465    2
1466    3
1467    2
1468    2
1469    2
Name: JobLvl, Length: 1356, dtype: int64

In [23]:
df.to_csv("../data/hr.csv", index=False)