In [12]:
import pandas as pd
import joblib

from sklearn.model_selection import train_test_split

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import GradientBoostingClassifier

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    confusion_matrix,
    classification_report
)

In [4]:
df = pd.read_csv("../data/hr.csv")

In [5]:
df

,Age,DailyRate,HomeDist,Education,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLvl,JobSatisfaction,MonthlyInc,...,JobRole_Manager,JobRole_Manufacturing Director,JobRole_Research Director,JobRole_Research Scientist,JobRole_Sales Executive,JobRole_Sales Representative,Marital_Married,Marital_Single,OverTime_Yes,Attrition
0,41,1102,1,2,2,94,3,2,4,5993,...,False,False,False,False,True,False,False,True,True,1
1,49,279,8,1,3,61,2,2,2,5130,...,False,False,False,True,False,False,True,False,False,0
2,37,1373,2,2,4,92,2,1,3,2090,...,False,False,False,False,False,False,False,True,True,1
3,33,1392,3,4,4,56,3,1,3,2909,...,False,False,False,True,False,False,True,False,True,0
4,27,591,2,1,1,40,3,1,2,3468,...,False,False,False,False,False,False,True,False,False,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1351,36,884,23,2,3,41,4,2,4,2571,...,False,False,False,False,False,False,True,False,False,0
1352,39,613,6,1,4,42,2,3,1,9991,...,False,False,False,False,False,False,True,False,False,0
1353,27,155,4,3,2,87,4,2,2,6142,...,False,True,False,False,False,False,True,False,True,0
1354,49,1023,2,3,4,63,2,2,2,5390,...,False,False,False,False,True,False,True,False,False,0
1355,34,628,8,3,2,82,4,2,3,4404,...,False,False,False,False,False,False,True,False,False,0

In [6]:
X = df.drop("Attrition", axis=1)
y = df["Attrition"]

In [7]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [15]:
# logistic regression
lr = LogisticRegression(max_iter=1000)

lr.fit(X_train, y_train)

y_pred_lr = lr.predict(X_test)

C:\Users\Ishika Singh Negi\AppData\Roaming\Python\Python314\site-packages\sklearn\linear_model\_logistic.py:599: ConvergenceWarning: lbfgs failed to converge after 1000 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=1000).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [14]:
print("Logistic Regression")

print("Accuracy :", accuracy_score(y_test, y_pred_lr))
print("Precision:", precision_score(y_test, y_pred_lr))
print("Recall   :", recall_score(y_test, y_pred_lr))
print("F1 Score :", f1_score(y_test, y_pred_lr))
print("ROC AUC  :", roc_auc_score(y_test, y_pred_lr))

print("\nConfusion Matrix")
print(confusion_matrix(y_test, y_pred_lr))

print("\nClassification Report")
print(classification_report(y_test, y_pred_lr))

Logistic Regression
Accuracy : 0.8529411764705882
Precision: 0.7058823529411765
Recall   : 0.2553191489361702
F1 Score : 0.375
ROC AUC  : 0.616548463356974

Confusion Matrix
[[220   5]
 [ 35  12]]

Classification Report
              precision    recall  f1-score   support

           0       0.86      0.98      0.92       225
           1       0.71      0.26      0.38        47

    accuracy                           0.85       272
   macro avg       0.78      0.62      0.65       272
weighted avg       0.84      0.85      0.82       272

In [16]:
# decision tree
dt = DecisionTreeClassifier(random_state=42)
dt.fit(X_train, y_train)
y_pred_dt = dt.predict(X_test)

In [17]:
print("Decision Tree")

print("Accuracy :", accuracy_score(y_test, y_pred_dt))
print("Precision:", precision_score(y_test, y_pred_dt))
print("Recall   :", recall_score(y_test, y_pred_dt))
print("F1 Score :", f1_score(y_test, y_pred_dt))
print("ROC AUC  :", roc_auc_score(y_test, y_pred_dt))

print(confusion_matrix(y_test, y_pred_dt))

print(classification_report(y_test, y_pred_dt))

Decision Tree
Accuracy : 0.7279411764705882
Precision: 0.2857142857142857
Recall   : 0.3829787234042553
F1 Score : 0.32727272727272727
ROC AUC  : 0.5914893617021277
[[180  45]
 [ 29  18]]
              precision    recall  f1-score   support

           0       0.86      0.80      0.83       225
           1       0.29      0.38      0.33        47

    accuracy                           0.73       272
   macro avg       0.57      0.59      0.58       272
weighted avg       0.76      0.73      0.74       272

In [18]:
#random forest 
rf = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

rf.fit(X_train, y_train)

y_pred_rf = rf.predict(X_test)

In [19]:
print("Random Forest")

print("Accuracy :", accuracy_score(y_test, y_pred_rf))
print("Precision:", precision_score(y_test, y_pred_rf))
print("Recall   :", recall_score(y_test, y_pred_rf))
print("F1 Score :", f1_score(y_test, y_pred_rf))
print("ROC AUC  :", roc_auc_score(y_test, y_pred_rf))

print(confusion_matrix(y_test, y_pred_rf))

print(classification_report(y_test, y_pred_rf))

Random Forest
Accuracy : 0.8492647058823529
Precision: 0.8
Recall   : 0.1702127659574468
F1 Score : 0.2807017543859649
ROC AUC  : 0.5806619385342789
[[223   2]
 [ 39   8]]
              precision    recall  f1-score   support

           0       0.85      0.99      0.92       225
           1       0.80      0.17      0.28        47

    accuracy                           0.85       272
   macro avg       0.83      0.58      0.60       272
weighted avg       0.84      0.85      0.81       272

In [20]:
results = pd.DataFrame({
    "Model": [
        "Logistic Regression",
        "Decision Tree",
        "Random Forest"
    ],
    "Accuracy": [
        accuracy_score(y_test, y_pred_lr),
        accuracy_score(y_test, y_pred_dt),
        accuracy_score(y_test, y_pred_rf)
    ],
    "Precision": [
        precision_score(y_test, y_pred_lr),
        precision_score(y_test, y_pred_dt),
        precision_score(y_test, y_pred_rf)
    ],
    "Recall": [
        recall_score(y_test, y_pred_lr),
        recall_score(y_test, y_pred_dt),
        recall_score(y_test, y_pred_rf)
    ],
    "F1 Score": [
        f1_score(y_test, y_pred_lr),
        f1_score(y_test, y_pred_dt),
        f1_score(y_test, y_pred_rf)
    ]
})

results.sort_values(by="Accuracy", ascending=False)

                 Model  Accuracy  Precision    Recall  F1 Score
0  Logistic Regression  0.852941   0.705882  0.255319  0.375000
2        Random Forest  0.849265   0.800000  0.170213  0.280702
1        Decision Tree  0.727941   0.285714  0.382979  0.327273

In [23]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    confusion_matrix,
    classification_report
)

# Train Logistic Regression
lr = LogisticRegression(
    max_iter=1000,
    random_state=42
)

lr.fit(X_train, y_train)

# Predictions
y_pred = lr.predict(X_test)

# Evaluation
print("Accuracy :", accuracy_score(y_test, y_pred))
print("Precision:", precision_score(y_test, y_pred))
print("Recall   :", recall_score(y_test, y_pred))
print("F1 Score :", f1_score(y_test, y_pred))
print("ROC AUC  :", roc_auc_score(y_test, y_pred))

print("\nConfusion Matrix")
print(confusion_matrix(y_test, y_pred))

print("\nClassification Report")
print(classification_report(y_test, y_pred))

Accuracy : 0.8529411764705882
Precision: 0.7058823529411765
Recall   : 0.2553191489361702
F1 Score : 0.375
ROC AUC  : 0.616548463356974

Confusion Matrix
[[220   5]
 [ 35  12]]

Classification Report
              precision    recall  f1-score   support

           0       0.86      0.98      0.92       225
           1       0.71      0.26      0.38        47

    accuracy                           0.85       272
   macro avg       0.78      0.62      0.65       272
weighted avg       0.84      0.85      0.82       272

C:\Users\Ishika Singh Negi\AppData\Roaming\Python\Python314\site-packages\sklearn\linear_model\_logistic.py:599: ConvergenceWarning: lbfgs failed to converge after 1000 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=1000).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [24]:
import joblib

joblib.dump(lr, "../models/model.pkl")

print("Model saved successfully!")

Model saved successfully!